/**
 * Static data for NewComponent
 * Auto-generated by html-to-react.js — edit freely.
 */

const data = {
  headings: {
    h2: "Built for Scale.\nTrusted by All.",
  },
  text: {
    since1999: "Since 1999",
    n49: "4.9★",
    averageRatingAcross1200Reviews: "Average rating across 1,200+ reviews",
    ourStory: "Our Story",
    mahaveertransWasFoundedIn1999Wit: "MahaveerTrans was founded in 1999 with a single idea: logistics should be transparent, fast, and accessible to every business. Today we operate in 40+ countries with 3,200 specialists and a proprietary TMS platform that gives clients full supply chain visibility.",
    ourAipoweredRoutingEngineSelects: "Our AI-powered routing engine selects the best combination of speed, cost, and carbon efficiency for every shipment — automatically optimised in real time.",
    iso9001Certified: "ISO 9001 Certified",
    iataAccredited: "IATA Accredited",
    n247ControlTower: "24/7 Control Tower",
    aipoweredRouting: "AI-Powered Routing",
    carbonNeutral2030: "Carbon Neutral 2030",
    realtimeVisibility: "Real-time Visibility",
  },
  images: [
    { src: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=900&q=80&auto=format&fit=crop", alt: "About" },
  ],
  links: [
    { href: "about.html", label: "Meet The Team →" },
  ],
};

export default data;